export const FETCH_PLAYERS = 'FETCH_PLAYERS';
export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_Q_DURATION = 'FETCH_Q_DURATION';
export const FETCH_APP_STATUS = 'FETCH_APP_STATUS';
export const ON_Q_DURATION_CHANGE = 'ON_Q_DURATION_CHANGE';
export const FETCH_ACTIVE_EVENT = 'FETCH_ACTIVE_EVENT';